apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: voltron-quarkus-8f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: voltron-quarkus-8f 
  name: voltron-quarkus-8f
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: voltron-quarkus-8f
    weight: 100 
